# Generated by Django 5.2.8 on 2025-11-19 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anonymous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages', models.CharField()),
                ('created', models.TimeField(auto_now=True)),
                ('update', models.TimeField(auto_now=True)),
                ('celebrant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anonymous', to='user_app.user')),
            ],
        ),
    ]
