# Generated by Django 5.2.8 on 2025-12-04 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymous',
            name='celebrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes', to='user_app.user'),
        ),
    ]
