# Generated by Django 5.2.8 on 2025-12-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_alter_anonymous_celebrant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymous',
            name='update',
        ),
        migrations.AddField(
            model_name='anonymous',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='anonymous',
            name='messages',
            field=models.CharField(max_length=500),
        ),
    ]
