# Generated by Django 5.2.8 on 2025-12-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_broadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broadcast',
            name='Broadcast_media',
            field=models.FileField(blank=True, null=True, upload_to='broadcasts/'),
        ),
        migrations.AlterField(
            model_name='broadcast',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
